networks:
  smfw_lan:
    external: true

services:
  elasticsearch:
    image: elasticsearch:8.17.3
    container_name: elasticsearch
    restart: always
    environment:
      - node.roles=master,data,ingest,ml,transform
      - xpack.security.enabled=false  # Disable security for local development
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=single-node
    ports:
      - '9200:9200'
    networks:
      - smfw_lan

  kibana:
    image: kibana:8.17.3
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch

    networks:
      - smfw_lan

